/*
 * This source file was generated by the Gradle 'init' task
 */
package tech.erben;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class AppTest {

    @Test
    @Tag("integration")
    public void test() {
        System.out.println("integration test");
    }

    @Test
    public void test2() {
        System.out.println("Non-integration test");
    }
}
